services:
  prometheus:
    volumes:
      - ../metrics/provisioning/prometheus/prometheus_l1_dev.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9091:9090"
  grafana:
    ports:
      - "3801:3000"
    volumes:
      - type: bind
        source: ../metrics/provisioning/grafana_provisioning/dashboards/dashboard_config_l1.yaml
        target: /etc/grafana/provisioning/dashboards/dashboard.yaml
